/****************************************************************************
*   Generated by ACUITY 3.11.0
*   Match ovxlib 1.0.8
*
*   Neural Network appliction network definition source file
****************************************************************************/
/*-------------------------------------------
                   Includes
 -------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>

#include "vsi_nn_pub.h"

#include "vnn_global.h"
#include "vnn_vgg16caffe.h"

/*-------------------------------------------
                   Macros
 -------------------------------------------*/

#define NEW_VXNODE(_node, _type, _in, _out, _uid) do {\
        _node = vsi_nn_AddNode( graph, _type, _in, _out, NULL );\
        _node->uid = (uint32_t)_uid; \
        if( NULL == _node ) {\
            goto error;\
        }\
    } while(0)

#define NEW_VIRTUAL_TENSOR(_id, _attr, _dtype) do {\
        memset( _attr.size, 0, VSI_NN_MAX_DIM_NUM * sizeof(uint32_t));\
        _attr.dim_num = VSI_NN_DIM_AUTO;\
        _attr.vtl = !VNN_APP_DEBUG;\
        _attr.is_const = FALSE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensor( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, NULL );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

// Set const tensor dims out of this macro.
#define NEW_CONST_TENSOR(_id, _attr, _dtype, _ofst, _size) do {\
        data = load_data( fp, _ofst, _size  );\
        _attr.vtl = FALSE;\
        _attr.is_const = TRUE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensor( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, data );\
        free( data );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

// Set generic tensor dims out of this macro.
#define NEW_NORM_TENSOR(_id, _attr, _dtype) do {\
        _attr.vtl = FALSE;\
        _attr.is_const = FALSE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensor( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, NULL );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

#define NET_NODE_NUM            (17)
#define NET_NORM_TENSOR_NUM     (2)
#define NET_CONST_TENSOR_NUM    (32)
#define NET_VIRTUAL_TENSOR_NUM  (17)
#define NET_TOTAL_TENSOR_NUM    (NET_NORM_TENSOR_NUM + NET_CONST_TENSOR_NUM + NET_VIRTUAL_TENSOR_NUM + 32)

/*-------------------------------------------
               Local Variables
 -------------------------------------------*/

/*-------------------------------------------
                  Functions
 -------------------------------------------*/
static void load_hw_config
    (
    vsi_nn_context_t ctx
    )
{
    ctx->config.evis.ver = VSI_NN_HW_EVIS_2;
    strncpy(ctx->config.target_name, "VIP8000", VSI_NN_MAX_TARGET_NAME);
}

static uint8_t* load_data
    (
    FILE  * fp,
    size_t  ofst,
    size_t  sz
    )
{
    uint8_t* data;
    int32_t ret;
    data = NULL;
    if( NULL == fp )
    {
        return NULL;
    }

    ret = fseek(fp, ofst, SEEK_SET);
    if (ret != 0)
    {
        VSILOGE("blob seek failure.");
        return NULL;
    }

    data = (uint8_t*)malloc(sz);
    if (data == NULL)
    {
        VSILOGE("buffer malloc failure.");
        return NULL;
    }
    ret = fread(data, 1, sz, fp);
    VSILOGI("Read %d data.", ret);
    return data;
} /* load_data() */

vsi_nn_graph_t * vnn_CreateVgg16Caffe
    (
    const char * data_file_name,
    vsi_nn_context_t in_ctx
    )
{
    vsi_status              status;
    vsi_bool                release_ctx;
    vsi_nn_context_t        ctx;
    vsi_nn_graph_t *        graph;
    vsi_nn_node_t *         node[NET_NODE_NUM];
    vsi_nn_tensor_id_t      norm_tensor[NET_NORM_TENSOR_NUM];
    vsi_nn_tensor_id_t      const_tensor[NET_CONST_TENSOR_NUM];
    vsi_nn_tensor_attr_t    attr;
    FILE *                  fp;
    uint8_t *               data;



    ctx = NULL;
    graph = NULL;
    status = VSI_FAILURE;

    fp = fopen( data_file_name, "rb" );
    if( NULL == fp )
    {
        VSILOGE( "Open file %s failed.", data_file_name );
        goto error;
    }

    if( NULL == in_ctx )
    {
        ctx = vsi_nn_CreateContext();
        load_hw_config(ctx);
    }
    else
    {
        ctx = in_ctx;
    }

    graph = vsi_nn_CreateGraph( ctx, NET_TOTAL_TENSOR_NUM, NET_NODE_NUM );
    if( NULL == graph )
    {
        VSILOGE( "Create graph fail." );
        goto error;
    }
    vsi_nn_SetGraphInputs( graph, NULL, 1 );
    vsi_nn_SetGraphOutputs( graph, NULL, 1 );

/*-----------------------------------------
  Register client ops
 -----------------------------------------*/


/*-----------------------------------------
  Node definitions
 -----------------------------------------*/

    /*-----------------------------------------
      lid       - conv1_1_1_relu1_1_2
      var       - node[0]
      name      - convolutionrelu
      operation - convolutionrelu
      in_shape  - [[224, 224, 3, 1]]
      out_shape - [[224, 224, 64, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[0], VSI_NN_OP_CONV_RELU, 3, 1, 2);
    node[0]->nn_param.conv2d.ksize[0] = 3;
    node[0]->nn_param.conv2d.ksize[1] = 3;
    node[0]->nn_param.conv2d.weights = 64;
    node[0]->nn_param.conv2d.stride[0] = 1;
    node[0]->nn_param.conv2d.stride[1] = 1;
    node[0]->nn_param.conv2d.pad[0] = 1;
    node[0]->nn_param.conv2d.pad[1] = 1;
    node[0]->nn_param.conv2d.pad[2] = 1;
    node[0]->nn_param.conv2d.pad[3] = 1;
    node[0]->nn_param.conv2d.group = 1;
    node[0]->nn_param.conv2d.dilation[0] = 1;
    node[0]->nn_param.conv2d.dilation[1] = 1;
    node[0]->vx_param.has_relu = TRUE;
    node[0]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[0]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[0]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv1_2_3_relu1_2_4_pool1_5
      var       - node[1]
      name      - convolutionrelupool
      operation - convolutionrelupool
      in_shape  - [[224, 224, 64, 1]]
      out_shape - [[112, 112, 64, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[1], VSI_NN_OP_CONV_RELU_POOL, 3, 1, 5);
    node[1]->nn_param.conv2d.ksize[0] = 3;
    node[1]->nn_param.conv2d.ksize[1] = 3;
    node[1]->nn_param.conv2d.weights = 64;
    node[1]->nn_param.conv2d.stride[0] = 1;
    node[1]->nn_param.conv2d.stride[1] = 1;
    node[1]->nn_param.conv2d.pad[0] = 1;
    node[1]->nn_param.conv2d.pad[1] = 1;
    node[1]->nn_param.conv2d.pad[2] = 1;
    node[1]->nn_param.conv2d.pad[3] = 1;
    node[1]->nn_param.conv2d.group = 1;
    node[1]->nn_param.conv2d.dilation[0] = 1;
    node[1]->nn_param.conv2d.dilation[1] = 1;
    node[1]->nn_param.pool.type = VX_CONVOLUTIONAL_NETWORK_POOLING_MAX;
    node[1]->nn_param.pool.ksize[0] = 2;
    node[1]->nn_param.pool.ksize[1] = 2;
    node[1]->nn_param.pool.stride[0] = 2;
    node[1]->nn_param.pool.stride[1] = 2;
    node[1]->nn_param.pool.pad[0] = 0;
    node[1]->nn_param.pool.pad[1] = 0;
    node[1]->nn_param.pool.pad[2] = 0;
    node[1]->nn_param.pool.pad[3] = 0;
    node[1]->vx_param.has_relu = TRUE;
    node[1]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[1]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[1]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv2_1_6_relu2_1_7
      var       - node[2]
      name      - convolutionrelu
      operation - convolutionrelu
      in_shape  - [[112, 112, 64, 1]]
      out_shape - [[112, 112, 128, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[2], VSI_NN_OP_CONV_RELU, 3, 1, 7);
    node[2]->nn_param.conv2d.ksize[0] = 3;
    node[2]->nn_param.conv2d.ksize[1] = 3;
    node[2]->nn_param.conv2d.weights = 128;
    node[2]->nn_param.conv2d.stride[0] = 1;
    node[2]->nn_param.conv2d.stride[1] = 1;
    node[2]->nn_param.conv2d.pad[0] = 1;
    node[2]->nn_param.conv2d.pad[1] = 1;
    node[2]->nn_param.conv2d.pad[2] = 1;
    node[2]->nn_param.conv2d.pad[3] = 1;
    node[2]->nn_param.conv2d.group = 1;
    node[2]->nn_param.conv2d.dilation[0] = 1;
    node[2]->nn_param.conv2d.dilation[1] = 1;
    node[2]->vx_param.has_relu = TRUE;
    node[2]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[2]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[2]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv2_2_8_relu2_2_9_pool2_10
      var       - node[3]
      name      - convolutionrelupool
      operation - convolutionrelupool
      in_shape  - [[112, 112, 128, 1]]
      out_shape - [[56, 56, 128, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[3], VSI_NN_OP_CONV_RELU_POOL, 3, 1, 10);
    node[3]->nn_param.conv2d.ksize[0] = 3;
    node[3]->nn_param.conv2d.ksize[1] = 3;
    node[3]->nn_param.conv2d.weights = 128;
    node[3]->nn_param.conv2d.stride[0] = 1;
    node[3]->nn_param.conv2d.stride[1] = 1;
    node[3]->nn_param.conv2d.pad[0] = 1;
    node[3]->nn_param.conv2d.pad[1] = 1;
    node[3]->nn_param.conv2d.pad[2] = 1;
    node[3]->nn_param.conv2d.pad[3] = 1;
    node[3]->nn_param.conv2d.group = 1;
    node[3]->nn_param.conv2d.dilation[0] = 1;
    node[3]->nn_param.conv2d.dilation[1] = 1;
    node[3]->nn_param.pool.type = VX_CONVOLUTIONAL_NETWORK_POOLING_MAX;
    node[3]->nn_param.pool.ksize[0] = 2;
    node[3]->nn_param.pool.ksize[1] = 2;
    node[3]->nn_param.pool.stride[0] = 2;
    node[3]->nn_param.pool.stride[1] = 2;
    node[3]->nn_param.pool.pad[0] = 0;
    node[3]->nn_param.pool.pad[1] = 0;
    node[3]->nn_param.pool.pad[2] = 0;
    node[3]->nn_param.pool.pad[3] = 0;
    node[3]->vx_param.has_relu = TRUE;
    node[3]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[3]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[3]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv3_1_11_relu3_1_12
      var       - node[4]
      name      - convolutionrelu
      operation - convolutionrelu
      in_shape  - [[56, 56, 128, 1]]
      out_shape - [[56, 56, 256, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[4], VSI_NN_OP_CONV_RELU, 3, 1, 12);
    node[4]->nn_param.conv2d.ksize[0] = 3;
    node[4]->nn_param.conv2d.ksize[1] = 3;
    node[4]->nn_param.conv2d.weights = 256;
    node[4]->nn_param.conv2d.stride[0] = 1;
    node[4]->nn_param.conv2d.stride[1] = 1;
    node[4]->nn_param.conv2d.pad[0] = 1;
    node[4]->nn_param.conv2d.pad[1] = 1;
    node[4]->nn_param.conv2d.pad[2] = 1;
    node[4]->nn_param.conv2d.pad[3] = 1;
    node[4]->nn_param.conv2d.group = 1;
    node[4]->nn_param.conv2d.dilation[0] = 1;
    node[4]->nn_param.conv2d.dilation[1] = 1;
    node[4]->vx_param.has_relu = TRUE;
    node[4]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[4]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[4]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv3_2_13_relu3_2_14
      var       - node[5]
      name      - convolutionrelu
      operation - convolutionrelu
      in_shape  - [[56, 56, 256, 1]]
      out_shape - [[56, 56, 256, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[5], VSI_NN_OP_CONV_RELU, 3, 1, 14);
    node[5]->nn_param.conv2d.ksize[0] = 3;
    node[5]->nn_param.conv2d.ksize[1] = 3;
    node[5]->nn_param.conv2d.weights = 256;
    node[5]->nn_param.conv2d.stride[0] = 1;
    node[5]->nn_param.conv2d.stride[1] = 1;
    node[5]->nn_param.conv2d.pad[0] = 1;
    node[5]->nn_param.conv2d.pad[1] = 1;
    node[5]->nn_param.conv2d.pad[2] = 1;
    node[5]->nn_param.conv2d.pad[3] = 1;
    node[5]->nn_param.conv2d.group = 1;
    node[5]->nn_param.conv2d.dilation[0] = 1;
    node[5]->nn_param.conv2d.dilation[1] = 1;
    node[5]->vx_param.has_relu = TRUE;
    node[5]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[5]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[5]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv3_3_15_relu3_3_16_pool3_17
      var       - node[6]
      name      - convolutionrelupool
      operation - convolutionrelupool
      in_shape  - [[56, 56, 256, 1]]
      out_shape - [[28, 28, 256, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[6], VSI_NN_OP_CONV_RELU_POOL, 3, 1, 17);
    node[6]->nn_param.conv2d.ksize[0] = 3;
    node[6]->nn_param.conv2d.ksize[1] = 3;
    node[6]->nn_param.conv2d.weights = 256;
    node[6]->nn_param.conv2d.stride[0] = 1;
    node[6]->nn_param.conv2d.stride[1] = 1;
    node[6]->nn_param.conv2d.pad[0] = 1;
    node[6]->nn_param.conv2d.pad[1] = 1;
    node[6]->nn_param.conv2d.pad[2] = 1;
    node[6]->nn_param.conv2d.pad[3] = 1;
    node[6]->nn_param.conv2d.group = 1;
    node[6]->nn_param.conv2d.dilation[0] = 1;
    node[6]->nn_param.conv2d.dilation[1] = 1;
    node[6]->nn_param.pool.type = VX_CONVOLUTIONAL_NETWORK_POOLING_MAX;
    node[6]->nn_param.pool.ksize[0] = 2;
    node[6]->nn_param.pool.ksize[1] = 2;
    node[6]->nn_param.pool.stride[0] = 2;
    node[6]->nn_param.pool.stride[1] = 2;
    node[6]->nn_param.pool.pad[0] = 0;
    node[6]->nn_param.pool.pad[1] = 0;
    node[6]->nn_param.pool.pad[2] = 0;
    node[6]->nn_param.pool.pad[3] = 0;
    node[6]->vx_param.has_relu = TRUE;
    node[6]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[6]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[6]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv4_1_18_relu4_1_19
      var       - node[7]
      name      - convolutionrelu
      operation - convolutionrelu
      in_shape  - [[28, 28, 256, 1]]
      out_shape - [[28, 28, 512, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[7], VSI_NN_OP_CONV_RELU, 3, 1, 19);
    node[7]->nn_param.conv2d.ksize[0] = 3;
    node[7]->nn_param.conv2d.ksize[1] = 3;
    node[7]->nn_param.conv2d.weights = 512;
    node[7]->nn_param.conv2d.stride[0] = 1;
    node[7]->nn_param.conv2d.stride[1] = 1;
    node[7]->nn_param.conv2d.pad[0] = 1;
    node[7]->nn_param.conv2d.pad[1] = 1;
    node[7]->nn_param.conv2d.pad[2] = 1;
    node[7]->nn_param.conv2d.pad[3] = 1;
    node[7]->nn_param.conv2d.group = 1;
    node[7]->nn_param.conv2d.dilation[0] = 1;
    node[7]->nn_param.conv2d.dilation[1] = 1;
    node[7]->vx_param.has_relu = TRUE;
    node[7]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[7]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[7]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv4_2_20_relu4_2_21
      var       - node[8]
      name      - convolutionrelu
      operation - convolutionrelu
      in_shape  - [[28, 28, 512, 1]]
      out_shape - [[28, 28, 512, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[8], VSI_NN_OP_CONV_RELU, 3, 1, 21);
    node[8]->nn_param.conv2d.ksize[0] = 3;
    node[8]->nn_param.conv2d.ksize[1] = 3;
    node[8]->nn_param.conv2d.weights = 512;
    node[8]->nn_param.conv2d.stride[0] = 1;
    node[8]->nn_param.conv2d.stride[1] = 1;
    node[8]->nn_param.conv2d.pad[0] = 1;
    node[8]->nn_param.conv2d.pad[1] = 1;
    node[8]->nn_param.conv2d.pad[2] = 1;
    node[8]->nn_param.conv2d.pad[3] = 1;
    node[8]->nn_param.conv2d.group = 1;
    node[8]->nn_param.conv2d.dilation[0] = 1;
    node[8]->nn_param.conv2d.dilation[1] = 1;
    node[8]->vx_param.has_relu = TRUE;
    node[8]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[8]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[8]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv4_3_22_relu4_3_23_pool4_24
      var       - node[9]
      name      - convolutionrelupool
      operation - convolutionrelupool
      in_shape  - [[28, 28, 512, 1]]
      out_shape - [[14, 14, 512, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[9], VSI_NN_OP_CONV_RELU_POOL, 3, 1, 24);
    node[9]->nn_param.conv2d.ksize[0] = 3;
    node[9]->nn_param.conv2d.ksize[1] = 3;
    node[9]->nn_param.conv2d.weights = 512;
    node[9]->nn_param.conv2d.stride[0] = 1;
    node[9]->nn_param.conv2d.stride[1] = 1;
    node[9]->nn_param.conv2d.pad[0] = 1;
    node[9]->nn_param.conv2d.pad[1] = 1;
    node[9]->nn_param.conv2d.pad[2] = 1;
    node[9]->nn_param.conv2d.pad[3] = 1;
    node[9]->nn_param.conv2d.group = 1;
    node[9]->nn_param.conv2d.dilation[0] = 1;
    node[9]->nn_param.conv2d.dilation[1] = 1;
    node[9]->nn_param.pool.type = VX_CONVOLUTIONAL_NETWORK_POOLING_MAX;
    node[9]->nn_param.pool.ksize[0] = 2;
    node[9]->nn_param.pool.ksize[1] = 2;
    node[9]->nn_param.pool.stride[0] = 2;
    node[9]->nn_param.pool.stride[1] = 2;
    node[9]->nn_param.pool.pad[0] = 0;
    node[9]->nn_param.pool.pad[1] = 0;
    node[9]->nn_param.pool.pad[2] = 0;
    node[9]->nn_param.pool.pad[3] = 0;
    node[9]->vx_param.has_relu = TRUE;
    node[9]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[9]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[9]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv5_1_25_relu5_1_26
      var       - node[10]
      name      - convolutionrelu
      operation - convolutionrelu
      in_shape  - [[14, 14, 512, 1]]
      out_shape - [[14, 14, 512, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[10], VSI_NN_OP_CONV_RELU, 3, 1, 26);
    node[10]->nn_param.conv2d.ksize[0] = 3;
    node[10]->nn_param.conv2d.ksize[1] = 3;
    node[10]->nn_param.conv2d.weights = 512;
    node[10]->nn_param.conv2d.stride[0] = 1;
    node[10]->nn_param.conv2d.stride[1] = 1;
    node[10]->nn_param.conv2d.pad[0] = 1;
    node[10]->nn_param.conv2d.pad[1] = 1;
    node[10]->nn_param.conv2d.pad[2] = 1;
    node[10]->nn_param.conv2d.pad[3] = 1;
    node[10]->nn_param.conv2d.group = 1;
    node[10]->nn_param.conv2d.dilation[0] = 1;
    node[10]->nn_param.conv2d.dilation[1] = 1;
    node[10]->vx_param.has_relu = TRUE;
    node[10]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[10]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[10]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv5_2_27_relu5_2_28
      var       - node[11]
      name      - convolutionrelu
      operation - convolutionrelu
      in_shape  - [[14, 14, 512, 1]]
      out_shape - [[14, 14, 512, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[11], VSI_NN_OP_CONV_RELU, 3, 1, 28);
    node[11]->nn_param.conv2d.ksize[0] = 3;
    node[11]->nn_param.conv2d.ksize[1] = 3;
    node[11]->nn_param.conv2d.weights = 512;
    node[11]->nn_param.conv2d.stride[0] = 1;
    node[11]->nn_param.conv2d.stride[1] = 1;
    node[11]->nn_param.conv2d.pad[0] = 1;
    node[11]->nn_param.conv2d.pad[1] = 1;
    node[11]->nn_param.conv2d.pad[2] = 1;
    node[11]->nn_param.conv2d.pad[3] = 1;
    node[11]->nn_param.conv2d.group = 1;
    node[11]->nn_param.conv2d.dilation[0] = 1;
    node[11]->nn_param.conv2d.dilation[1] = 1;
    node[11]->vx_param.has_relu = TRUE;
    node[11]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[11]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[11]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - conv5_3_29_relu5_3_30_pool5_31
      var       - node[12]
      name      - convolutionrelupool
      operation - convolutionrelupool
      in_shape  - [[14, 14, 512, 1]]
      out_shape - [[7, 7, 512, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[12], VSI_NN_OP_CONV_RELU_POOL, 3, 1, 31);
    node[12]->nn_param.conv2d.ksize[0] = 3;
    node[12]->nn_param.conv2d.ksize[1] = 3;
    node[12]->nn_param.conv2d.weights = 512;
    node[12]->nn_param.conv2d.stride[0] = 1;
    node[12]->nn_param.conv2d.stride[1] = 1;
    node[12]->nn_param.conv2d.pad[0] = 1;
    node[12]->nn_param.conv2d.pad[1] = 1;
    node[12]->nn_param.conv2d.pad[2] = 1;
    node[12]->nn_param.conv2d.pad[3] = 1;
    node[12]->nn_param.conv2d.group = 1;
    node[12]->nn_param.conv2d.dilation[0] = 1;
    node[12]->nn_param.conv2d.dilation[1] = 1;
    node[12]->nn_param.pool.type = VX_CONVOLUTIONAL_NETWORK_POOLING_MAX;
    node[12]->nn_param.pool.ksize[0] = 2;
    node[12]->nn_param.pool.ksize[1] = 2;
    node[12]->nn_param.pool.stride[0] = 2;
    node[12]->nn_param.pool.stride[1] = 2;
    node[12]->nn_param.pool.pad[0] = 0;
    node[12]->nn_param.pool.pad[1] = 0;
    node[12]->nn_param.pool.pad[2] = 0;
    node[12]->nn_param.pool.pad[3] = 0;
    node[12]->vx_param.has_relu = TRUE;
    node[12]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[12]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[12]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - fc6_32_relu6_33
      var       - node[13]
      name      - fullconnectrelu
      operation - fullconnectrelu
      in_shape  - [[7, 7, 512, 1]]
      out_shape - [[4096, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[13], VSI_NN_OP_FCL_RELU, 3, 1, 33);
    node[13]->nn_param.fcl.weights = 4096;
    node[13]->vx_param.has_relu = TRUE;
    node[13]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[13]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[13]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - fc7_35_relu7_36
      var       - node[14]
      name      - fullconnectrelu
      operation - fullconnectrelu
      in_shape  - [[4096, 1]]
      out_shape - [[4096, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[14], VSI_NN_OP_FCL_RELU, 3, 1, 36);
    node[14]->nn_param.fcl.weights = 4096;
    node[14]->vx_param.has_relu = TRUE;
    node[14]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[14]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[14]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - trans_fc8_38
      var       - node[15]
      name      - fullconnectrelu
      operation - fullconnectrelu
      in_shape  - [[4096, 1]]
      out_shape - [[1000, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[15], VSI_NN_OP_FCL_RELU, 3, 1, 38);
    node[15]->nn_param.fcl.weights = 1000;
    node[15]->vx_param.has_relu = FALSE;
    node[15]->vx_param.overflow_policy = VX_CONVERT_POLICY_WRAP;
    node[15]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[15]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - prob_39
      var       - node[16]
      name      - prob
      operation - softmax
      in_shape  - [[1000, 1]]
      out_shape - [[1000, 1]]
    -----------------------------------------*/
    NEW_VXNODE(node[16], VSI_NN_OP_SOFTMAX, 1, 1, 39);


/*-----------------------------------------
  Tensor initialize
 -----------------------------------------*/
    attr.dtype.fmt = VSI_NN_DIM_FMT_NCHW;
    /* @input_0:out0 */
    attr.size[0] = 224;
    attr.size[1] = 224;
    attr.size[2] = 3;
    attr.size[3] = 1;
    attr.dim_num = 4;
    attr.dtype.fl = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_NORM_TENSOR(norm_tensor[0], attr, VSI_NN_TYPE_INT8);

    /* @output_40:out0 */
    attr.size[0] = 1000;
    attr.size[1] = 1;
    attr.dim_num = 2;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_NONE;
    NEW_NORM_TENSOR(norm_tensor[1], attr, VSI_NN_TYPE_FLOAT16);



    /* @conv1_1_1_relu1_1_2:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 3;
    attr.size[3] = 64;
    attr.dim_num = 4;
    attr.dtype.fl = 7;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[0], attr, VSI_NN_TYPE_INT8, 256, 1728);

    /* @conv1_1_1_relu1_1_2:bias */
    attr.size[0] = 64;
    attr.dim_num = 1;
    attr.dtype.fl = 7;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[1], attr, VSI_NN_TYPE_INT32, 0, 256);

    /* @conv1_2_3_relu1_2_4_pool1_5:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 64;
    attr.size[3] = 64;
    attr.dim_num = 4;
    attr.dtype.fl = 8;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[2], attr, VSI_NN_TYPE_INT8, 2240, 36864);

    /* @conv1_2_3_relu1_2_4_pool1_5:bias */
    attr.size[0] = 64;
    attr.dim_num = 1;
    attr.dtype.fl = 5;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[3], attr, VSI_NN_TYPE_INT32, 1984, 256);

    /* @conv2_1_6_relu2_1_7:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 64;
    attr.size[3] = 128;
    attr.dim_num = 4;
    attr.dtype.fl = 8;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[4], attr, VSI_NN_TYPE_INT8, 39616, 73728);

    /* @conv2_1_6_relu2_1_7:bias */
    attr.size[0] = 128;
    attr.dim_num = 1;
    attr.dtype.fl = 3;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[5], attr, VSI_NN_TYPE_INT32, 39104, 512);

    /* @conv2_2_8_relu2_2_9_pool2_10:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 128;
    attr.size[3] = 128;
    attr.dim_num = 4;
    attr.dtype.fl = 8;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[6], attr, VSI_NN_TYPE_INT8, 113856, 147456);

    /* @conv2_2_8_relu2_2_9_pool2_10:bias */
    attr.size[0] = 128;
    attr.dim_num = 1;
    attr.dtype.fl = 2;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[7], attr, VSI_NN_TYPE_INT32, 113344, 512);

    /* @conv3_1_11_relu3_1_12:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 128;
    attr.size[3] = 256;
    attr.dim_num = 4;
    attr.dtype.fl = 7;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[8], attr, VSI_NN_TYPE_INT8, 262336, 294912);

    /* @conv3_1_11_relu3_1_12:bias */
    attr.size[0] = 256;
    attr.dim_num = 1;
    attr.dtype.fl = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[9], attr, VSI_NN_TYPE_INT32, 261312, 1024);

    /* @conv3_2_13_relu3_2_14:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 256;
    attr.size[3] = 256;
    attr.dim_num = 4;
    attr.dtype.fl = 8;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[10], attr, VSI_NN_TYPE_INT8, 558272, 589824);

    /* @conv3_2_13_relu3_2_14:bias */
    attr.size[0] = 256;
    attr.dim_num = 1;
    attr.dtype.fl = 1;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[11], attr, VSI_NN_TYPE_INT32, 557248, 1024);

    /* @conv3_3_15_relu3_3_16_pool3_17:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 256;
    attr.size[3] = 256;
    attr.dim_num = 4;
    attr.dtype.fl = 8;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[12], attr, VSI_NN_TYPE_INT8, 1149120, 589824);

    /* @conv3_3_15_relu3_3_16_pool3_17:bias */
    attr.size[0] = 256;
    attr.dim_num = 1;
    attr.dtype.fl = 1;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[13], attr, VSI_NN_TYPE_INT32, 1148096, 1024);

    /* @conv4_1_18_relu4_1_19:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 256;
    attr.size[3] = 512;
    attr.dim_num = 4;
    attr.dtype.fl = 8;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[14], attr, VSI_NN_TYPE_INT8, 1740992, 1179648);

    /* @conv4_1_18_relu4_1_19:bias */
    attr.size[0] = 512;
    attr.dim_num = 1;
    attr.dtype.fl = 1;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[15], attr, VSI_NN_TYPE_INT32, 1738944, 2048);

    /* @conv4_2_20_relu4_2_21:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 512;
    attr.size[3] = 512;
    attr.dim_num = 4;
    attr.dtype.fl = 8;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[16], attr, VSI_NN_TYPE_INT8, 2922688, 2359296);

    /* @conv4_2_20_relu4_2_21:bias */
    attr.size[0] = 512;
    attr.dim_num = 1;
    attr.dtype.fl = 2;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[17], attr, VSI_NN_TYPE_INT32, 2920640, 2048);

    /* @conv4_3_22_relu4_3_23_pool4_24:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 512;
    attr.size[3] = 512;
    attr.dim_num = 4;
    attr.dtype.fl = 8;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[18], attr, VSI_NN_TYPE_INT8, 5284032, 2359296);

    /* @conv4_3_22_relu4_3_23_pool4_24:bias */
    attr.size[0] = 512;
    attr.dim_num = 1;
    attr.dtype.fl = 3;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[19], attr, VSI_NN_TYPE_INT32, 5281984, 2048);

    /* @conv5_1_25_relu5_1_26:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 512;
    attr.size[3] = 512;
    attr.dim_num = 4;
    attr.dtype.fl = 9;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[20], attr, VSI_NN_TYPE_INT8, 7645376, 2359296);

    /* @conv5_1_25_relu5_1_26:bias */
    attr.size[0] = 512;
    attr.dim_num = 1;
    attr.dtype.fl = 5;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[21], attr, VSI_NN_TYPE_INT32, 7643328, 2048);

    /* @conv5_2_27_relu5_2_28:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 512;
    attr.size[3] = 512;
    attr.dim_num = 4;
    attr.dtype.fl = 9;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[22], attr, VSI_NN_TYPE_INT8, 10006720, 2359296);

    /* @conv5_2_27_relu5_2_28:bias */
    attr.size[0] = 512;
    attr.dim_num = 1;
    attr.dtype.fl = 6;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[23], attr, VSI_NN_TYPE_INT32, 10004672, 2048);

    /* @conv5_3_29_relu5_3_30_pool5_31:weight */
    attr.size[0] = 3;
    attr.size[1] = 3;
    attr.size[2] = 512;
    attr.size[3] = 512;
    attr.dim_num = 4;
    attr.dtype.fl = 8;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[24], attr, VSI_NN_TYPE_INT8, 12368064, 2359296);

    /* @conv5_3_29_relu5_3_30_pool5_31:bias */
    attr.size[0] = 512;
    attr.dim_num = 1;
    attr.dtype.fl = 6;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[25], attr, VSI_NN_TYPE_INT32, 12366016, 2048);

    /* @fc6_32_relu6_33:weight */
    attr.size[0] = 25088;
    attr.size[1] = 4096;
    attr.dim_num = 2;
    attr.dtype.fl = 12;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[26], attr, VSI_NN_TYPE_INT8, 14743744, 102760448);

    /* @fc6_32_relu6_33:bias */
    attr.size[0] = 4096;
    attr.dim_num = 1;
    attr.dtype.fl = 11;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[27], attr, VSI_NN_TYPE_INT32, 14727360, 16384);

    /* @fc7_35_relu7_36:weight */
    attr.size[0] = 4096;
    attr.size[1] = 4096;
    attr.dim_num = 2;
    attr.dtype.fl = 11;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[28], attr, VSI_NN_TYPE_INT8, 117520576, 16777216);

    /* @fc7_35_relu7_36:bias */
    attr.size[0] = 4096;
    attr.dim_num = 1;
    attr.dtype.fl = 12;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[29], attr, VSI_NN_TYPE_INT32, 117504192, 16384);

    /* @trans_fc8_38:weight */
    attr.size[0] = 4096;
    attr.size[1] = 1000;
    attr.dim_num = 2;
    attr.dtype.fl = 11;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[30], attr, VSI_NN_TYPE_INT8, 134301792, 4096000);

    /* @trans_fc8_38:bias */
    attr.size[0] = 1000;
    attr.dim_num = 1;
    attr.dtype.fl = 14;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_CONST_TENSOR(const_tensor[31], attr, VSI_NN_TYPE_INT32, 134297792, 4000);



    /* @conv1_1_1_relu1_1_2:out0 */
    attr.dtype.fl = -3;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[0]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv1_2_3_relu1_2_4_pool1_5:out0 */
    attr.dtype.fl = -5;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[1]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv2_1_6_relu2_1_7:out0 */
    attr.dtype.fl = -6;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[2]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv2_2_8_relu2_2_9_pool2_10:out0 */
    attr.dtype.fl = -7;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[3]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv3_1_11_relu3_1_12:out0 */
    attr.dtype.fl = -7;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[4]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv3_2_13_relu3_2_14:out0 */
    attr.dtype.fl = -7;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[5]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv3_3_15_relu3_3_16_pool3_17:out0 */
    attr.dtype.fl = -7;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[6]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv4_1_18_relu4_1_19:out0 */
    attr.dtype.fl = -6;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[7]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv4_2_20_relu4_2_21:out0 */
    attr.dtype.fl = -5;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[8]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv4_3_22_relu4_3_23_pool4_24:out0 */
    attr.dtype.fl = -4;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[9]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv5_1_25_relu5_1_26:out0 */
    attr.dtype.fl = -3;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[10]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv5_2_27_relu5_2_28:out0 */
    attr.dtype.fl = -2;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[11]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @conv5_3_29_relu5_3_30_pool5_31:out0 */
    attr.dtype.fl = -1;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[12]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @fc6_32_relu6_33:out0 */
    attr.dtype.fl = 1;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[13]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @fc7_35_relu7_36:out0 */
    attr.dtype.fl = 3;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[14]->output.tensors[0], attr, VSI_NN_TYPE_INT8);

    /* @trans_fc8_38:out0 */
    attr.dtype.fl = 1;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_DFP;
    NEW_VIRTUAL_TENSOR(node[15]->output.tensors[0], attr, VSI_NN_TYPE_INT8);



/*-----------------------------------------
  Connection initialize
 -----------------------------------------*/
    node[0]->input.tensors[0] = norm_tensor[0];
    node[16]->output.tensors[0] = norm_tensor[1];

    /* conv1_1_1_relu1_1_2 */
    node[0]->input.tensors[1] = const_tensor[0]; /* data_weight */
    node[0]->input.tensors[2] = const_tensor[1]; /* data_bias */

    /* conv1_2_3_relu1_2_4_pool1_5 */
    node[1]->input.tensors[0] = node[0]->output.tensors[0];
    node[1]->input.tensors[1] = const_tensor[2]; /* data_weight */
    node[1]->input.tensors[2] = const_tensor[3]; /* data_bias */

    /* conv2_1_6_relu2_1_7 */
    node[2]->input.tensors[0] = node[1]->output.tensors[0];
    node[2]->input.tensors[1] = const_tensor[4]; /* data_weight */
    node[2]->input.tensors[2] = const_tensor[5]; /* data_bias */

    /* conv2_2_8_relu2_2_9_pool2_10 */
    node[3]->input.tensors[0] = node[2]->output.tensors[0];
    node[3]->input.tensors[1] = const_tensor[6]; /* data_weight */
    node[3]->input.tensors[2] = const_tensor[7]; /* data_bias */

    /* conv3_1_11_relu3_1_12 */
    node[4]->input.tensors[0] = node[3]->output.tensors[0];
    node[4]->input.tensors[1] = const_tensor[8]; /* data_weight */
    node[4]->input.tensors[2] = const_tensor[9]; /* data_bias */

    /* conv3_2_13_relu3_2_14 */
    node[5]->input.tensors[0] = node[4]->output.tensors[0];
    node[5]->input.tensors[1] = const_tensor[10]; /* data_weight */
    node[5]->input.tensors[2] = const_tensor[11]; /* data_bias */

    /* conv3_3_15_relu3_3_16_pool3_17 */
    node[6]->input.tensors[0] = node[5]->output.tensors[0];
    node[6]->input.tensors[1] = const_tensor[12]; /* data_weight */
    node[6]->input.tensors[2] = const_tensor[13]; /* data_bias */

    /* conv4_1_18_relu4_1_19 */
    node[7]->input.tensors[0] = node[6]->output.tensors[0];
    node[7]->input.tensors[1] = const_tensor[14]; /* data_weight */
    node[7]->input.tensors[2] = const_tensor[15]; /* data_bias */

    /* conv4_2_20_relu4_2_21 */
    node[8]->input.tensors[0] = node[7]->output.tensors[0];
    node[8]->input.tensors[1] = const_tensor[16]; /* data_weight */
    node[8]->input.tensors[2] = const_tensor[17]; /* data_bias */

    /* conv4_3_22_relu4_3_23_pool4_24 */
    node[9]->input.tensors[0] = node[8]->output.tensors[0];
    node[9]->input.tensors[1] = const_tensor[18]; /* data_weight */
    node[9]->input.tensors[2] = const_tensor[19]; /* data_bias */

    /* conv5_1_25_relu5_1_26 */
    node[10]->input.tensors[0] = node[9]->output.tensors[0];
    node[10]->input.tensors[1] = const_tensor[20]; /* data_weight */
    node[10]->input.tensors[2] = const_tensor[21]; /* data_bias */

    /* conv5_2_27_relu5_2_28 */
    node[11]->input.tensors[0] = node[10]->output.tensors[0];
    node[11]->input.tensors[1] = const_tensor[22]; /* data_weight */
    node[11]->input.tensors[2] = const_tensor[23]; /* data_bias */

    /* conv5_3_29_relu5_3_30_pool5_31 */
    node[12]->input.tensors[0] = node[11]->output.tensors[0];
    node[12]->input.tensors[1] = const_tensor[24]; /* data_weight */
    node[12]->input.tensors[2] = const_tensor[25]; /* data_bias */

    /* fc6_32_relu6_33 */
    node[13]->input.tensors[0] = node[12]->output.tensors[0];
    node[13]->input.tensors[1] = const_tensor[26]; /* data_weight */
    node[13]->input.tensors[2] = const_tensor[27]; /* data_bias */

    /* fc7_35_relu7_36 */
    node[14]->input.tensors[0] = node[13]->output.tensors[0];
    node[14]->input.tensors[1] = const_tensor[28]; /* data_weight */
    node[14]->input.tensors[2] = const_tensor[29]; /* data_bias */

    /* trans_fc8_38 */
    node[15]->input.tensors[0] = node[14]->output.tensors[0];
    node[15]->input.tensors[1] = const_tensor[30]; /* data_weight */
    node[15]->input.tensors[2] = const_tensor[31]; /* data_bias */

    /* prob_39 */
    node[16]->input.tensors[0] = node[15]->output.tensors[0];



    graph->input.tensors[0] = norm_tensor[0];
    graph->output.tensors[0] = norm_tensor[1];


    status = vsi_nn_SetupGraph( graph, FALSE );
    if( VSI_FAILURE == status )
    {
        goto error;
    }

    fclose( fp );

    return graph;

error:
    if( NULL != fp )
    {
        fclose( fp );
    }

    release_ctx = ( NULL == in_ctx );
    vnn_ReleaseVgg16Caffe( graph, release_ctx );

    return NULL;
} /* vsi_nn_CreateVgg16Caffe() */

void vnn_ReleaseVgg16Caffe
    (
    vsi_nn_graph_t * graph,
    vsi_bool release_ctx
    )
{
    vsi_nn_context_t ctx;
    if( NULL != graph )
    {
        ctx = graph->ctx;
        vsi_nn_ReleaseGraph( &graph );

        /*-----------------------------------------
        Unregister client ops
        -----------------------------------------*/
        

        if( release_ctx )
        {
            vsi_nn_ReleaseContext( &ctx );
        }
    }
} /* vsi_nn_ReleaseVgg16Caffe() */

